version: '3.8'

services:
  gateway:
    image: gateway:dev
    container_name: gateway-dev
    build:
      context: gateway
      dockerfile: ./Dockerfile
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - ./gateway:/app
  analytics:
    image: analytics:dev
    container_name: analytics-dev
    build:
      context: analytics
      dockerfile: ./Dockerfile
    expose:
      - 5001
    ports:
      - "5001:3000"
    volumes:
      - ./analytics:/app
