version: '3.8'

services:
  gateway:
    image: gateway:prod
    container_name: gateway-prod
    build:
      context: gateway
      dockerfile: ./Dockerfile.prod
  analytics:
    image: analytics:prod
    container_name: analytics-prod
    build:
      context: analytics
      dockerfile: ./Dockerfile.prod
