version: '3.8'

services:
  gateway:
    image: gateway:prod
    container_name: gateway-prod
    build:
      context: gateway
      dockerfile: ./Dockerfile.prod
  analytics:
    image: analytics:prod
    container_name: analytics-prod
    build:
      context: analytics
      dockerfile: ./Dockerfile # TODO: temp fix, use Dockerfile.prod (see https://github.com/bartolomej/moonland/issues/11)
