version: '3.8'

services:
  api:
    container_name: gateway
    build:
      context: gateway
      dockerfile: ./Dockerfile
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - ./gateway:/app
