version: '3.8'

services:
  gateway:
    image: gateway:prod
    container_name: gateway-prod
    build:
      context: gateway
      dockerfile: ./Dockerfile.prod
    expose:
      - 5000
    ports:
      - "5000:5000"
  analytics:
    image: analytics:prod
    container_name: analytics-prod
    build:
      context: analytics
      dockerfile: ./Dockerfile.prod
    expose:
      - 5001
    ports:
      - "5001:3000"
