FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet clean

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

CMD dotnet out/shitcoin-analysis-backend.dll